### ISSUE TITLE
[Features reaction] keep the drawing tool

### ISSUE THREAD

**Issue by JE-Amouel** [daledesilva/obsidian_ink#23]
hi,
first of , your plugin is awesome.
I followed all the YouTube videos that you posted on YouTube about the development of ink, I was particularly interested in the video where you presented the hand drawing tool, I understood that you wanted to remove the functionality, perhaps so as not to compete with excalidraw, which I find very honorable, the thing is that ink and excalidraw are extensions which can be complementary without having to compete,
excalidraw offers a note-taking philosophy based on hand drawing on its own canvas with a whole ecosystem of plugins called scripts, which can be perfect for organizing a large project, ink offers more simplicity when it comes to illustrating quickly an idea with the maximum of simplicity, which is ideal when you want to organize the way of managing a large project, easily modifiable drawings interleave between text, do not remove the hand drawing option I found it simple and very practical, we are not all Picasso when it comes to drawing a straight line, a perfect square, or a circle, especially since we are not all on the tablet format or but if that were the case, we would not have all a stylus.
ink perfectly integrates the main mode, it would be good to take advantage of it, at worst give us a draft version, draft ink, where you would let all these ideas run their course with the users' opinions, and the main version (ink), where we would be entitled to your final version.

**Comment by ichmoimeyo** [comment]
Yes, please keep the drawing tool.

Some "brainstorming" notes I start by inserting a drawing section and underneath it a handwriting section.
... drawing section: a quick mind map
... handwriting section: distilling the main points of the mind map, outline style.

I can "insert existing" drawing(&/or handwriting) sections into other notes.
Occasionally I will then [OCR the handwriting part](https://github.com/daledesilva/obsidian_ink/issues/18). 

Although I have Nebo installed I am starting to use your plugin more as it is right there in Obsidian when I need it.

Thanks again for developing this wonderful plugin.

**Comment by daledesilva** [comment]
Thank you @JE-Amouel and @ichmoimeyo .

@JE-Amouel , I 100% agree with everything you described and thanks for following along with the diaries.

My comment regarding potentially taking out the drawing aspect of Ink wasn't in regard to competing with Excalidraw (I see it as a different use case as you do), but rather the more large features I put in the more work it will be to maintain — I was concerned that supporting drawing might lead to less time developing features that are writing focussed.

That being said, I'm not taking it out, however, it will likely move at a slower pace than the writing features, and will keep its functionality minimal and focussed on freeform stylus use rather than adding diagrams and symbols etc. Sounds like that's what you like about it too, which is great 😊

In regard to a draft version, this has somewhat been implemented now, actually. Since Ink is now listed in the community plugins section, you can install it from there, or if you want to stay on the 'bleeding edge' of features being tested (and bugs been ironed out), you can stick with the BRAT version. 

@ichmoimeyo Thanks for your comment about Nebo. Great to hear that this use case scratches your itch right where you need it :)
