### ISSUE TITLE
While drawing, canvas area extends behind buttons at top.

### ISSUE THREAD

**Issue by MrComputron** [daledesilva/obsidian_ink#33]
**Describe the bug**
Drawing canvas extends behind the buttons at top of ink area, making it possible to draw without seeing what is being drawn.

**Video or screenshots**

https://github.com/daledesilva/obsidian_ink/assets/46870771/363bccc5-573d-4747-b020-a98d4e082d2c

**To Reproduce**
If you're video or screenshots need more context, describe the steps reproduce the behavior:
1. New drawing section
2. Begin drawing, going up to the button area

**Expected behavior**
Expected canvas to end below the buttons, maintaining a clear separation between the two

**Desktop (please complete the following information):**
- **Device & OS**: Samsung S23 Ultra, Android 14, OneUI 6.1
- **Plugin version**: 0.1.172 (via Obsidian, not BRAT)
- **Obsidian version**: 1.5.12

**Additional context**

Screen record has a few notes that are not directly related, eg. The button sizes are not uniform, non visible border.

**Comment by daledesilva** [comment]
Thanks for reporting 🙂

Drawing behind the buttons is expected behaviour. In your video, you've scroll the page down so that the canvas is cropped half off the top of the screen. In this instance, the buttons move purposely down over the canvas to allow you to still select them when needed. If this happens just scroll the page a bit up again.

In regard to the border and the alignment, these are hopefully already fixed in the new version. Please update and check.

You may have to uninstall the plug-in and reinstall it to update to 0.1.19
You shouldn't need BRAT as I just update it in the main stream last night.

Lemme know how you go!

**Comment by MrComputron** [comment]
Hi Dale, buttons looking very clean now and behavior is as you noted (at top until scroll).

Border is **very** faint, I wonder if this can be darker or maybe it is possible via CSS to customize in themes or snippets.

**Comment by daledesilva** [comment]
Good to hear.
I'll close this issue as that's complete. If you like you can create another feature request for the line contrast, but that's on my list of updates anyway :)
