### ISSUE TITLE
Improving handwriting performance on Boox devices

### ISSUE THREAD

**Issue by lvovalexej** [daledesilva/obsidian_ink#70]
Hi! thank you for an amazing plugin! 
I think the usability concept is spot on, but what makes it barely usable on Boox devices is a latency for handwriting - not only does it lag like a full word behind my input it also skips some strokes and interpolates between what it did register making it almost not recognizable.

My understanding is that for Boox devices they have a specific SDK to make handwriting performance on par with their proprietary apps (which is pretty good).

Is there a chance that could be integrated?

p.s. as far as i know boox are the only eink devices which can run obsidian and support handwriting, so the scope of this proposal is basically everybody liking eink and obsidian 

p.p.s. Maybe this can help:
https://github.com/onyx-intl/OnyxAndroidDemo

**Comment by MDsza** [comment]
Hi! First of all, I want to express my appreciation for this amazing plugin @daledesilva! The concept and approach are spot on and perfectly align with a workflow I've been envisioning for quite some time now.

My setup includes macOS, iOS, iPadOS, and an Android device—specifically the Onyx Boox Air 3C. The Onyx Boox has a remarkable handwriting engine, but unfortunately, the plugin is currently not quite usable on this device, mainly due to significant latency issues. It often lags behind my input and occasionally skips strokes, which makes the handwriting experience less than ideal.

Given that Onyx provides a specific SDK to optimize handwriting performance on their devices, I sincerely hope that porting the plugin to support Onyx Boox devices is possible and, ideally, something that's already being considered.

**Comment by daledesilva** [comment]
Hi @lvovalexej and @MDsza 
This is likely very tricky for me to fix as even if the code linked above works, I don't believe I could include native code like that from within an html and javascript based Obsidian plugin (I'll probably have to organise with the Obsidian team to try and include).

However, I've done some googling and I think there might also be a fix from your end. Could you please try following this guide...
https://gist.github.com/calliecameron/b3c62c601d255630468bd493380e3b7e?permalink_comment_id=4993606

Let me know how you go!

**Comment by simeneide** [comment]
> Hi [@lvovalexej](https://github.com/lvovalexej) and [@MDsza](https://github.com/MDsza) This is likely very tricky for me to fix as even if the code linked above works, I don't believe I could include native code like that from within an html and javascript based Obsidian plugin (I'll probably have to organise with the Obsidian team to try and include).
> 
> However, I've done some googling and I think there might also be a fix from your end. Could you please try following this guide... https://gist.github.com/calliecameron/b3c62c601d255630468bd493380e3b7e?permalink_comment_id=4993606
> 
> Let me know how you go!

@lvovalexej @MDsza Did you try this potential fix?

**Comment by lvovalexej** [comment]
@simeneide as i wrote in https://github.com/daledesilva/obsidian_ink/issues/76 rooting openned a posibility of a potential fix, but i requires figuring out a class name which is responsible for rendering (i guess) handling inside presumably a web rendering engine which obisidian or tldraw on android uses. and i haven't found that information on the internet nor am i sufficiently familiar with java to do it myself.

**Comment by lvovalexej** [comment]
@simeneide @MDsza this trick does work. check https://github.com/daledesilva/obsidian_ink/issues/76 for details
